### ISSUE TITLE
Very excited prospective users

### ISSUE THREAD

**Issue by jpinedaf** [vlas-sokolov/bayesian-ngc1333#3]
Hi Vlas,

People really want to try it! Could you please make the repo public? or add @low-sky, @rfriesen, and @mcyc to the repo so that they can play with it?

**Comment by vlas-sokolov** [comment]
Welcome @everyone! The repo is public now. @jpinedaf can I open up [pyspecnest](https://github.com/vlas-sokolov/pyspecnest) as well then?

**Comment by vlas-sokolov** [comment]
Done! Several useful features I originally planned for the public release are still missing (see [this project](https://github.com/vlas-sokolov/pyspecnest/projects/1)), but they are all just unfinished user-friendliness ideas. Enjoy, and let me know if you need any input!

**Comment by jpinedaf** [comment]
Awesome!! cool.
