### ISSUE TITLE
Error in generating K and Z cubes for 3-component fits

### ISSUE THREAD

**Issue by SpandanCh** [vlas-sokolov/bayesian-ngc1333#9]
@vlas-sokolov , I am recently getting an error when trying to generate the K and Z cubes using `make_KZ_cubes.py`, when I include the 3-component fits. Here is the error message that I get :
```
Traceback (most recent call last):
  File "make_KZ_cubes.py", line 38, in <module>
    make_KZ_cubes([0, 1, 2])
  File "make_KZ_cubes.py", line 31, in make_KZ_cubes
    hdu_K = cube_K(writeto=file_Ks, **cube_KZ_kwargs)
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 335, in cube_K
    Zs = cube_Z(shape, rms, data, peaks=peaks, origin=origin,
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 415, in cube_Z
    Z_xy = lnZ_xy(x=x, y=y, peaks=peaks, lnZ0=ln_Z0, **kwargs)
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 205, in lnZ_xy
    ln_Z_npeaks = [ln_Z(a) for a in peak_stats]
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 205, in <listcomp>
    ln_Z_npeaks = [ln_Z(a) for a in peak_stats]
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 306, in ln_Z
    stats = get_stats(a, 'fast')
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 299, in get_stats
    return get_global_evidence(a)
  File "/home/spandan/anaconda3/envs/fit-bayesian/lib/python3.8/site-packages/pyspecnest/chaincrunch.py", line 223, in get_global_evidence
    a._read_error_into_dict(lines[1], stats)
IndexError: list index out of range
```

If I use the script using `make_KZ_cubes([0, 1, 2])`, there is no issues. I only get the error when I use `make_KZ_cubes([0, 1, 2, 3])`. 
I should note that this a recent issue I have been facing with my new setup, and in my old setup, I never encountered this. The `3-.txt` files exist, and when I run `make_KZ_cubes.py`, I see the script going through the `3-.txt` files. So I am not sure what the issue could be.

I checked the imported cube_K and cube_Z from `pyspecnest.chaincrunch`, too, and both have `peaks=[0, 1, 2, 3]`.

Any idea why I am suddenly getting this error?

**Comment by vlas-sokolov** [comment]
It fails reading more than one line from a summary file. Could be a parsing error of MultiNest's output files, perhaps the format has changed somewhat in the last five years? Also, make sure that the [stats file](https://github.com/vlas-sokolov/pyspecnest/blob/master/pyspecnest/chaincrunch.py#L220) is not empty, something tells me that could be an issue.

**Comment by SpandanCh** [comment]
I just ran the fits on a very small subcube around the snr peak, and ran the script. It generated the K and Z cubes without any issue. So the MultiNest version should not be an issue. 

I checked the `3-stats.dat` files, and some of them were indeed empty. Removing them seems to have done the trick. Thank you !!
Can you maybe suggest why some of the pixels had empty `3-stats.dat` files? I never stopped the fit process in the middle, nor did it complain anywhere during the process.

**Comment by vlas-sokolov** [comment]
To be completely honest, I have no idea why they'd be empty - never had that issue before. Those are generated by MultiNest, perhaps you could catch Johannes Buchner and ask him, if he's still in MPE?

**Comment by SpandanCh** [comment]
Actually, _I_ am not in MPE anymore 😅. I moved to Korea last year.
Anyway, this was the first time I faced this issue, too. And for now, just removing the empty stats files and re-running those pixels seems to have done it. If it occurs again later, I will try to follow up with him via Github.

**Comment by vlas-sokolov** [comment]
Ah, didn't know that, congrats! And yes, that makes sense, hopefully it will behave better in the future!

**Comment by SpandanCh** [comment]
Thanks!
As the issue is (for now) resolved, I will mark it closed. Thanks a lot for the help!
